// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSJLkJw1b-M015hOnVKvf53txcxrTzMpI',
    appId: '1:699805247251:web:c7a9bc386eb14d8a525ce6',
    messagingSenderId: '699805247251',
    projectId: 'imdb-app-be26e',
    authDomain: 'imdb-app-be26e.firebaseapp.com',
    storageBucket: 'imdb-app-be26e.appspot.com',
    measurementId: 'G-E0WY0DYY1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3XHg4lq5eXDKHIL6DhMarzToEu6uWDAQ',
    appId: '1:699805247251:android:edf57032a127d92c525ce6',
    messagingSenderId: '699805247251',
    projectId: 'imdb-app-be26e',
    storageBucket: 'imdb-app-be26e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPDCDDi2621sPgJkEm3vW_YdHajKoxjCM',
    appId: '1:699805247251:ios:8378a14d49aa6dbe525ce6',
    messagingSenderId: '699805247251',
    projectId: 'imdb-app-be26e',
    storageBucket: 'imdb-app-be26e.appspot.com',
    iosClientId: '699805247251-gablibkem6oetfqk51kfkc2n3l31jgg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPDCDDi2621sPgJkEm3vW_YdHajKoxjCM',
    appId: '1:699805247251:ios:8378a14d49aa6dbe525ce6',
    messagingSenderId: '699805247251',
    projectId: 'imdb-app-be26e',
    storageBucket: 'imdb-app-be26e.appspot.com',
    iosClientId: '699805247251-gablibkem6oetfqk51kfkc2n3l31jgg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbApp',
  );
}
